#!/usr/bin/env php
<?php

use PhpRepos\FileManager\Path;
use PhpRepos\TestRunner\TestResults;
use PhpRepos\TestRunner\TestRun;
use function PhpRepos\Cli\Output\line;
use function PhpRepos\Cli\Output\write;
use function PhpRepos\Datatype\Arr\filter;
use function PhpRepos\FileManager\Directories\ls_all;
use function PhpRepos\FileManager\Files\exists;
use function PhpRepos\FileManager\Paths\append;
use function PhpRepos\FileManager\Paths\root;

$parameter = function(string $name, ?string $default = null): ?string
{
    $input = getopt('', [$name . '::']);

    if (count($input) === 0) {
        global $argv;

        // Search for the named parameter and extract its value
        $input = array_reduce($argv, function ($carry, $argument) use ($name) {
            return str_starts_with($argument, "--$name=")
                ? [$name => str_replace("--$name=", '', $argument)]
                : $carry;
        }, []);
    }

    return $input[$name] ?? $default;
};

$root = Path::from_string(root());

$tests_directory = Path::from(append($root, $parameter('directory', 'Tests')));

$filter = $parameter('filter', '');
$phpkg_import_file = append($root, getenv('PHPKG_IMPORT_FILE') ?: 'phpkg.imports.php');
$record = TestResults\insert(new TestRun($root, $filter));

$tests = filter(ls_all($tests_directory), fn (string $file) => str_contains($file, $filter) && str_ends_with($file, 'Test.php'));

$import_file = __DIR__ . '/Imports.php';
$descriptor_spec = [
    0 => ["pipe", "r"],  // stdin
    1 => ["pipe", "w"],  // stdout
    2 => ["pipe", "w"],  // stderr
    3 => ["pipe", "w"],  // custom
];

$base_command = "env ";
$base_command .= exists($phpkg_import_file) ? "PHPKG_IMPORT_FILE=$phpkg_import_file " : '';
$base_command .= "TEST_RESULT_ID=$record->id php -d auto_prepend_file=$import_file ";

foreach ($tests as $test_file) {
    $command = "{$base_command}{$test_file}";

    $process = proc_open($command, $descriptor_spec, $pipes);

    if (is_resource($process)) {
        stream_set_blocking($pipes[1], false);
        stream_set_blocking($pipes[2], false);
        stream_set_blocking($pipes[3], false);

        while (true) {
            $status = proc_get_status($process);

            $output_chunk = fread($pipes[1], 8192);
            if ($output_chunk !== false && $output_chunk !== '') {
                write($output_chunk);
            }

            $error_output_chunk = fread($pipes[2], 8192);
            if ($error_output_chunk !== false && $error_output_chunk !== '') {
                write($error_output_chunk);
            }

            $custom_output_chunk = fread($pipes[3], 8192);
            if ($custom_output_chunk !== false && $custom_output_chunk !== '') {
                write($custom_output_chunk);
            }

            if (!$status['running']) {
                break;
            }
        }

        fclose($pipes[1]);
        fclose($pipes[2]);
        proc_close($process);
    }
}

$record = TestResults\find($record->id);
$cases = count($record->cases);
$successes = count(array_filter($record->cases, fn ($case) => $case['successful']));
$failed = count(array_filter($record->cases, fn ($case) => ! $case['successful']));

line(PHP_EOL . "cases: $cases, success: $successes, failed: $failed");

exit($failed);
